Models/ErrorViewModel.cs
using System;

namespace FinalProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ScoreContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.Models
{
    public class ScoreContext : DbContext
    {
        public ScoreContext(DbContextOptions<ScoreContext> options)
            : base(options)
        { }

        public DbSet<ScoreModel> Scores { get; set; }
    }
}

Models/ScoreModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.Models
{
    public class ScoreModel
    {
        [Key]
        public int ScoreId { get; set; }
        [Required(ErrorMessage = "Please enter a date.")]
        public string Date { get; set; }
        [Required(ErrorMessage = "Please enter a score.")]
        public int? Score { get; set; }
        
    }
}

Controllers/HomeController.cs
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ContactsShaw.Controllers
{
    public class HomeController : Controller
    {
        // Home Controller
        private ScoreContext context { get; set; }
        public HomeController(ScoreContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            var scores = context.Scores.OrderBy(c => c.Score).ToList();
            return View(scores);
        }
        // custom routing attribute
        [Route("Attribute")]
        public IActionResult Attribute()
        {
            return Content("Home controller, Attribute action");
        }
        // Default
        public IActionResult List(string Name)
        {
            return Content("name=" + Name);
        }
        // custom routing rules
        public IActionResult List2(string id = "All", int page = 1)
        {
            return Content("id=" + id + " page=" + page);
        }
    }
}

Controllers/ScoreController.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProject.Controllers
{
    public class ScoreController : Controller
    {
        private ScoreContext context { get; set; }

        public ScoreController(ScoreContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            // Viewbag
            return View("Edit", new ScoreModel());
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            // Viewbag
            var scores = context.Scores.Find(id);
            return View(scores);
        }
        [HttpPost]
        public IActionResult Edit(ScoreModel scoreVariable)
        {
            if (ModelState.IsValid)
            {
                if (scoreVariable.ScoreId == 0)
                    context.Scores.Add(scoreVariable);
                else
                    context.Scores.Update(scoreVariable);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (scoreVariable.ScoreId == 0) ? "Add" : "Edit";
                // Viewbag
                return View(scoreVariable);
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var contact = context.Scores.Find(id);
            return View(contact);
        }
        [HttpPost]
        public IActionResult Delete(ScoreModel score)
        {
            context.Scores.Remove(score);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Home/Index.cshtml
@model List<ScoreModel>
@{
    ViewData["Title"] = "Home Page";
}
<span class="badge badge-light">@Model</span>
<vc:contact></vc:contact>

<a asp-controller="Score" asp-action="Add">Add New Score</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Date</th>

            <th>Score</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var scoreModel in Model)
        {
            <tr>
                <td>@scoreModel.Date</td>
                <td>@scoreModel.Score</td>
                <td>
                    <a asp-controller="Score" asp-action="Edit" asp-route-id="@scoreModel.ScoreId">Edit</a>
                    <a asp-controller="Score" asp-action="Delete" asp-route-id="@scoreModel.ScoreId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Index.cshtml
@model List<ScoreModel>
@{
    ViewData["Title"] = "Home Page";
}
<span class="badge badge-light">@Model</span>
<vc:contact></vc:contact>

<a asp-controller="Score" asp-action="Add">Add New Contact</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>

            <th>Name</th>
            <th>Phone Number</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var scoreModel in Model)
        {
            <tr>
                <td>@scoreModel.Date</td>
                <td>@scoreModel.Score</td>
                <td>
                    <a asp-controller="Contact" asp-action="Edit" asp-route-id="@scoreModel.ScoreId">Edit</a>
                    <a asp-controller="Contact" asp-action="Delete" asp-route-id="@scoreModel.ScoreId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Score/Delete.cshtml
@model ScoreModel
@{
    ViewBag.Title = "Delete Score";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Score (@Model.Date) </h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="ScoreId" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Views/Score/Edit.cshtml
@model ScoreModel
@{
    string title = ViewBag.Action + " Score";
    ViewBag.Title = title;
}

<h2>@ViewBag.title</h2>

<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger" />

    <div class="form-group">
        <label asp-for="Score">Score</label>
        <input asp-for="Score" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Date">Date</label>
        <input asp-for="Date" class="form-control" />
    </div>

    <input type="hidden" asp-for="ScoreId" />

    <button type="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>

</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>